version: '3.3'
services:
  zoo1:
    image: zookeeper:3.5.3-beta
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    image: zookeeper:3.5.3-beta
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    image: zookeeper:3.5.3-beta
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181

  kafka1:
    image: wurstmeister/kafka:1.0.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181/wut/kafka"
    depends_on: [zoo1, zoo2, zoo3]
  kafka2:
    image: wurstmeister/kafka:1.0.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181/wut/kafka"
    depends_on: [zoo1, zoo2, zoo3]
  kafka3:
    image: wurstmeister/kafka:1.0.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181/wut/kafka"
    depends_on: [zoo1, zoo2, zoo3]

  dotnet:
    build:
      context: Kafka
